// Copyright 2025 Canonical Ltd. All rights reserved.
// Licensed under the AGPLv3, see LICENCE file for details.

// Code generated by go generate; DO NOT EDIT.

package v4_0_1

import (
	"time"
)

type AgentBinaryStore struct {
	Version         string `db:"version"`
	ArchitectureId  int64  `db:"architecture_id"`
	ObjectStoreUuid string `db:"object_store_uuid"`
}

type AgentStream struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type AgentVersion struct {
	StreamId      int64  `db:"stream_id"`
	TargetVersion string `db:"target_version"`
	LatestVersion string `db:"latest_version"`
}

type AnnotationApplication struct {
	Uuid  string `db:"uuid"`
	Key   string `db:"key"`
	Value string `db:"value"`
}

type AnnotationCharm struct {
	Uuid  string `db:"uuid"`
	Key   string `db:"key"`
	Value string `db:"value"`
}

type AnnotationMachine struct {
	Uuid  string `db:"uuid"`
	Key   string `db:"key"`
	Value string `db:"value"`
}

type AnnotationModel struct {
	Key   string `db:"key"`
	Value string `db:"value"`
}

type AnnotationStorageFilesystem struct {
	Uuid  string `db:"uuid"`
	Key   string `db:"key"`
	Value string `db:"value"`
}

type AnnotationStorageInstance struct {
	Uuid  string `db:"uuid"`
	Key   string `db:"key"`
	Value string `db:"value"`
}

type AnnotationStorageVolume struct {
	Uuid  string `db:"uuid"`
	Key   string `db:"key"`
	Value string `db:"value"`
}

type AnnotationUnit struct {
	Uuid  string `db:"uuid"`
	Key   string `db:"key"`
	Value string `db:"value"`
}

type Application struct {
	Uuid                 string `db:"uuid"`
	Name                 string `db:"name"`
	LifeId               int64  `db:"life_id"`
	CharmUuid            string `db:"charm_uuid"`
	CharmModifiedVersion int64  `db:"charm_modified_version"`
	CharmUpgradeOnError  *bool  `db:"charm_upgrade_on_error"`
	SpaceUuid            string `db:"space_uuid"`
}

type ApplicationAgent struct {
	ApplicationUuid         string  `db:"application_uuid"`
	PasswordHashAlgorithmId *string `db:"password_hash_algorithm_id"`
	PasswordHash            *string `db:"password_hash"`
}

type ApplicationChannel struct {
	ApplicationUuid string  `db:"application_uuid"`
	Track           *string `db:"track"`
	Risk            string  `db:"risk"`
	Branch          *string `db:"branch"`
}

type ApplicationConfig struct {
	ApplicationUuid string  `db:"application_uuid"`
	Key             string  `db:"key"`
	TypeId          int64   `db:"type_id"`
	Value           *string `db:"value"`
}

type ApplicationConfigHash struct {
	ApplicationUuid string `db:"application_uuid"`
	Sha256          string `db:"sha256"`
}

type ApplicationConstraint struct {
	ApplicationUuid string  `db:"application_uuid"`
	ConstraintUuid  *string `db:"constraint_uuid"`
}

type ApplicationController struct {
	ApplicationUuid string `db:"application_uuid"`
}

type ApplicationEndpoint struct {
	Uuid              string  `db:"uuid"`
	ApplicationUuid   string  `db:"application_uuid"`
	SpaceUuid         *string `db:"space_uuid"`
	CharmRelationUuid string  `db:"charm_relation_uuid"`
}

type ApplicationExposedEndpointCidr struct {
	ApplicationUuid         string  `db:"application_uuid"`
	ApplicationEndpointUuid *string `db:"application_endpoint_uuid"`
	Cidr                    string  `db:"cidr"`
}

type ApplicationExposedEndpointSpace struct {
	ApplicationUuid         string  `db:"application_uuid"`
	ApplicationEndpointUuid *string `db:"application_endpoint_uuid"`
	SpaceUuid               string  `db:"space_uuid"`
}

type ApplicationExtraEndpoint struct {
	ApplicationUuid       string  `db:"application_uuid"`
	SpaceUuid             *string `db:"space_uuid"`
	CharmExtraBindingUuid string  `db:"charm_extra_binding_uuid"`
}

type ApplicationPlatform struct {
	ApplicationUuid string  `db:"application_uuid"`
	OsId            string  `db:"os_id"`
	Channel         *string `db:"channel"`
	ArchitectureId  int64   `db:"architecture_id"`
}

type ApplicationRemoteConsumer struct {
	OfferConnectionUuid     string `db:"offer_connection_uuid"`
	OffererApplicationUuid  string `db:"offerer_application_uuid"`
	ConsumerApplicationUuid string `db:"consumer_application_uuid"`
	ConsumerModelUuid       string `db:"consumer_model_uuid"`
	LifeId                  int64  `db:"life_id"`
}

type ApplicationRemoteOfferer struct {
	Uuid                  string  `db:"uuid"`
	LifeId                int64   `db:"life_id"`
	ApplicationUuid       string  `db:"application_uuid"`
	OfferUuid             string  `db:"offer_uuid"`
	OfferUrl              string  `db:"offer_url"`
	OffererControllerUuid *string `db:"offerer_controller_uuid"`
	OffererModelUuid      string  `db:"offerer_model_uuid"`
	Macaroon              string  `db:"macaroon"`
}

type ApplicationRemoteOffererRelationMacaroon struct {
	RelationUuid string `db:"relation_uuid"`
	Macaroon     string `db:"macaroon"`
}

type ApplicationRemoteOffererStatus struct {
	ApplicationRemoteOffererUuid string     `db:"application_remote_offerer_uuid"`
	StatusId                     int64      `db:"status_id"`
	Message                      *string    `db:"message"`
	Data                         *string    `db:"data"`
	UpdatedAt                    *time.Time `db:"updated_at"`
}

type ApplicationResource struct {
	ResourceUuid    string `db:"resource_uuid"`
	ApplicationUuid string `db:"application_uuid"`
}

type ApplicationScale struct {
	ApplicationUuid string `db:"application_uuid"`
	Scale           *int64 `db:"scale"`
	ScaleTarget     *int64 `db:"scale_target"`
	Scaling         *bool  `db:"scaling"`
}

type ApplicationSetting struct {
	ApplicationUuid string `db:"application_uuid"`
	Trust           *bool  `db:"trust"`
}

type ApplicationStatus struct {
	ApplicationUuid string     `db:"application_uuid"`
	StatusId        int64      `db:"status_id"`
	Message         *string    `db:"message"`
	Data            *string    `db:"data"`
	UpdatedAt       *time.Time `db:"updated_at"`
}

type ApplicationStorageDirective struct {
	ApplicationUuid string `db:"application_uuid"`
	CharmUuid       string `db:"charm_uuid"`
	StorageName     string `db:"storage_name"`
	StoragePoolUuid string `db:"storage_pool_uuid"`
	SizeMib         int64  `db:"size_mib"`
	Count           int64  `db:"count"`
}

type ApplicationWorkloadVersion struct {
	ApplicationUuid string `db:"application_uuid"`
	Version         string `db:"version"`
}

type Architecture struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type AvailabilityZone struct {
	Uuid string `db:"uuid"`
	Name string `db:"name"`
}

type AvailabilityZoneSubnet struct {
	AvailabilityZoneUuid string `db:"availability_zone_uuid"`
	SubnetUuid           string `db:"subnet_uuid"`
}

type BlockCommand struct {
	Uuid               string  `db:"uuid"`
	BlockCommandTypeId int64   `db:"block_command_type_id"`
	Message            *string `db:"message"`
}

type BlockCommandType struct {
	Id       *int64 `db:"id"`
	NameType string `db:"name_type"`
}

type BlockDevice struct {
	Uuid               string  `db:"uuid"`
	MachineUuid        string  `db:"machine_uuid"`
	Name               *string `db:"name"`
	HardwareId         *string `db:"hardware_id"`
	Wwn                *string `db:"wwn"`
	SerialId           *string `db:"serial_id"`
	BusAddress         *string `db:"bus_address"`
	SizeMib            *int64  `db:"size_mib"`
	MountPoint         *string `db:"mount_point"`
	InUse              *bool   `db:"in_use"`
	FilesystemLabel    *string `db:"filesystem_label"`
	HostFilesystemUuid *string `db:"host_filesystem_uuid"`
	FilesystemType     *string `db:"filesystem_type"`
}

type BlockDeviceLinkDevice struct {
	BlockDeviceUuid string `db:"block_device_uuid"`
	MachineUuid     string `db:"machine_uuid"`
	Name            string `db:"name"`
}

type ChangeLog struct {
	Id          *int64    `db:"id"`
	EditTypeId  int64     `db:"edit_type_id"`
	NamespaceId int64     `db:"namespace_id"`
	Changed     string    `db:"changed"`
	CreatedAt   time.Time `db:"created_at"`
}

type ChangeLogEditType struct {
	Id       *int64  `db:"id"`
	EditType *string `db:"edit_type"`
}

type ChangeLogNamespace struct {
	Id          *int64  `db:"id"`
	Namespace   *string `db:"namespace"`
	Description *string `db:"description"`
}

type ChangeLogWitness struct {
	ControllerId string    `db:"controller_id"`
	LowerBound   int64     `db:"lower_bound"`
	UpperBound   int64     `db:"upper_bound"`
	UpdatedAt    time.Time `db:"updated_at"`
}

type Charm struct {
	Uuid            string    `db:"uuid"`
	ArchivePath     *string   `db:"archive_path"`
	ObjectStoreUuid *string   `db:"object_store_uuid"`
	Available       *bool     `db:"available"`
	Version         *string   `db:"version"`
	LxdProfile      *string   `db:"lxd_profile"`
	SourceId        int64     `db:"source_id"`
	Revision        int64     `db:"revision"`
	ArchitectureId  *int64    `db:"architecture_id"`
	ReferenceName   string    `db:"reference_name"`
	CreateTime      time.Time `db:"create_time"`
}

type CharmAction struct {
	CharmUuid      string  `db:"charm_uuid"`
	Key            string  `db:"key"`
	Description    *string `db:"description"`
	Parallel       *bool   `db:"parallel"`
	ExecutionGroup *string `db:"execution_group"`
	Params         *string `db:"params"`
}

type CharmCategory struct {
	CharmUuid  string `db:"charm_uuid"`
	ArrayIndex int64  `db:"array_index"`
	Value      string `db:"value"`
}

type CharmConfig struct {
	CharmUuid    string  `db:"charm_uuid"`
	Key          string  `db:"key"`
	TypeId       *string `db:"type_id"`
	DefaultValue *string `db:"default_value"`
	Description  *string `db:"description"`
}

type CharmConfigType struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type CharmContainer struct {
	CharmUuid string  `db:"charm_uuid"`
	Key       string  `db:"key"`
	Resource  *string `db:"resource"`
	Uid       *int64  `db:"uid"`
	Gid       *int64  `db:"gid"`
}

type CharmContainerMount struct {
	ArrayIndex        int64   `db:"array_index"`
	CharmUuid         string  `db:"charm_uuid"`
	CharmContainerKey *string `db:"charm_container_key"`
	Storage           *string `db:"storage"`
	Location          *string `db:"location"`
}

type CharmDevice struct {
	CharmUuid   string  `db:"charm_uuid"`
	Key         string  `db:"key"`
	Name        *string `db:"name"`
	Description *string `db:"description"`
	DeviceType  *string `db:"device_type"`
	CountMin    int64   `db:"count_min"`
	CountMax    int64   `db:"count_max"`
}

type CharmDownloadInfo struct {
	CharmUuid          string  `db:"charm_uuid"`
	ProvenanceId       int64   `db:"provenance_id"`
	CharmhubIdentifier *string `db:"charmhub_identifier"`
	DownloadUrl        string  `db:"download_url"`
	DownloadSize       int64   `db:"download_size"`
}

type CharmExtraBinding struct {
	Uuid      string `db:"uuid"`
	CharmUuid string `db:"charm_uuid"`
	Name      string `db:"name"`
}

type CharmHash struct {
	CharmUuid  string `db:"charm_uuid"`
	HashKindId int64  `db:"hash_kind_id"`
	Hash       string `db:"hash"`
}

type CharmManifestBase struct {
	CharmUuid        string  `db:"charm_uuid"`
	ArrayIndex       int64   `db:"array_index"`
	NestedArrayIndex int64   `db:"nested_array_index"`
	OsId             *int64  `db:"os_id"`
	Track            *string `db:"track"`
	Risk             string  `db:"risk"`
	Branch           *string `db:"branch"`
	ArchitectureId   *int64  `db:"architecture_id"`
}

type CharmMetadata struct {
	CharmUuid      string  `db:"charm_uuid"`
	Name           string  `db:"name"`
	Description    *string `db:"description"`
	Summary        *string `db:"summary"`
	Subordinate    bool    `db:"subordinate"`
	MinJujuVersion *string `db:"min_juju_version"`
	RunAsId        *int64  `db:"run_as_id"`
	Assumes        *string `db:"assumes"`
}

type CharmProvenance struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type CharmRelation struct {
	Uuid      string  `db:"uuid"`
	CharmUuid string  `db:"charm_uuid"`
	Name      string  `db:"name"`
	RoleId    int64   `db:"role_id"`
	ScopeId   int64   `db:"scope_id"`
	Interface *string `db:"interface"`
	Optional  *bool   `db:"optional"`
	Capacity  *int64  `db:"capacity"`
}

type CharmRelationRole struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type CharmRelationScope struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type CharmResource struct {
	CharmUuid   string  `db:"charm_uuid"`
	Name        string  `db:"name"`
	KindId      int64   `db:"kind_id"`
	Path        *string `db:"path"`
	Description *string `db:"description"`
}

type CharmResourceKind struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type CharmRunAsKind struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type CharmSource struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type CharmStorage struct {
	CharmUuid      string  `db:"charm_uuid"`
	Name           string  `db:"name"`
	Description    *string `db:"description"`
	StorageKindId  int64   `db:"storage_kind_id"`
	Shared         bool    `db:"shared"`
	ReadOnly       *bool   `db:"read_only"`
	CountMin       int64   `db:"count_min"`
	CountMax       int64   `db:"count_max"`
	MinimumSizeMib *int64  `db:"minimum_size_mib"`
	Location       *string `db:"location"`
}

type CharmStorageKind struct {
	Id   *int64 `db:"id"`
	Kind string `db:"kind"`
}

type CharmStorageProperty struct {
	CharmUuid        string `db:"charm_uuid"`
	CharmStorageName string `db:"charm_storage_name"`
	ArrayIndex       int64  `db:"array_index"`
	Value            string `db:"value"`
}

type CharmTag struct {
	CharmUuid  string `db:"charm_uuid"`
	ArrayIndex int64  `db:"array_index"`
	Value      string `db:"value"`
}

type CharmTerm struct {
	CharmUuid  string `db:"charm_uuid"`
	ArrayIndex int64  `db:"array_index"`
	Value      string `db:"value"`
}

type Constraint struct {
	Uuid             string  `db:"uuid"`
	Arch             *string `db:"arch"`
	CpuCores         *int64  `db:"cpu_cores"`
	CpuPower         *int64  `db:"cpu_power"`
	Mem              *int64  `db:"mem"`
	RootDisk         *int64  `db:"root_disk"`
	RootDiskSource   *string `db:"root_disk_source"`
	InstanceRole     *string `db:"instance_role"`
	InstanceType     *string `db:"instance_type"`
	ContainerTypeId  *int64  `db:"container_type_id"`
	VirtType         *string `db:"virt_type"`
	AllocatePublicIp *int64  `db:"allocate_public_ip"`
	ImageId          *string `db:"image_id"`
}

type ConstraintSpace struct {
	ConstraintUuid string `db:"constraint_uuid"`
	Space          string `db:"space"`
	Exclude        bool   `db:"exclude"`
}

type ConstraintTag struct {
	ConstraintUuid string `db:"constraint_uuid"`
	Tag            string `db:"tag"`
}

type ConstraintZone struct {
	ConstraintUuid string `db:"constraint_uuid"`
	Zone           string `db:"zone"`
}

type ContainerType struct {
	Id    *int64 `db:"id"`
	Value string `db:"value"`
}

type DeviceConstraint struct {
	Uuid            string `db:"uuid"`
	ApplicationUuid string `db:"application_uuid"`
	Name            string `db:"name"`
	Type            string `db:"type"`
	Count           *int64 `db:"count"`
}

type DeviceConstraintAttribute struct {
	DeviceConstraintUuid string `db:"device_constraint_uuid"`
	Key                  string `db:"key"`
	Value                string `db:"value"`
}

type FqdnAddress struct {
	Uuid    string `db:"uuid"`
	Address string `db:"address"`
	ScopeId int64  `db:"scope_id"`
}

type HashKind struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type HostnameAddress struct {
	Uuid     string `db:"uuid"`
	Hostname string `db:"hostname"`
	ScopeId  int64  `db:"scope_id"`
}

type InstanceTag struct {
	MachineUuid string `db:"machine_uuid"`
	Tag         string `db:"tag"`
}

type IpAddress struct {
	Uuid         string  `db:"uuid"`
	NetNodeUuid  string  `db:"net_node_uuid"`
	DeviceUuid   string  `db:"device_uuid"`
	AddressValue string  `db:"address_value"`
	SubnetUuid   *string `db:"subnet_uuid"`
	TypeId       int64   `db:"type_id"`
	ConfigTypeId int64   `db:"config_type_id"`
	OriginId     int64   `db:"origin_id"`
	ScopeId      int64   `db:"scope_id"`
	IsSecondary  *bool   `db:"is_secondary"`
	IsShadow     *bool   `db:"is_shadow"`
}

type IpAddressConfigType struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type IpAddressOrigin struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type IpAddressScope struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type IpAddressType struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type K8sPod struct {
	UnitUuid   string `db:"unit_uuid"`
	ProviderId string `db:"provider_id"`
}

type K8sPodPort struct {
	UnitUuid string `db:"unit_uuid"`
	Port     string `db:"port"`
}

type K8sPodStatus struct {
	UnitUuid  string     `db:"unit_uuid"`
	StatusId  int64      `db:"status_id"`
	Message   *string    `db:"message"`
	Data      *string    `db:"data"`
	UpdatedAt *time.Time `db:"updated_at"`
}

type K8sPodStatusValue struct {
	Id     *int64 `db:"id"`
	Status string `db:"status"`
}

type K8sService struct {
	Uuid            string `db:"uuid"`
	ApplicationUuid string `db:"application_uuid"`
	NetNodeUuid     string `db:"net_node_uuid"`
	ProviderId      string `db:"provider_id"`
}

type Life struct {
	Id    *int64 `db:"id"`
	Value string `db:"value"`
}

type LinkLayerDevice struct {
	Uuid              string  `db:"uuid"`
	NetNodeUuid       string  `db:"net_node_uuid"`
	Name              string  `db:"name"`
	Mtu               *int64  `db:"mtu"`
	MacAddress        *string `db:"mac_address"`
	DeviceTypeId      int64   `db:"device_type_id"`
	VirtualPortTypeId int64   `db:"virtual_port_type_id"`
	IsAutoStart       bool    `db:"is_auto_start"`
	IsEnabled         bool    `db:"is_enabled"`
	IsDefaultGateway  bool    `db:"is_default_gateway"`
	GatewayAddress    *string `db:"gateway_address"`
	VlanTag           int64   `db:"vlan_tag"`
}

type LinkLayerDeviceDnsAddress struct {
	DeviceUuid string `db:"device_uuid"`
	DnsAddress string `db:"dns_address"`
}

type LinkLayerDeviceDnsDomain struct {
	DeviceUuid   string `db:"device_uuid"`
	SearchDomain string `db:"search_domain"`
}

type LinkLayerDeviceParent struct {
	DeviceUuid string `db:"device_uuid"`
	ParentUuid string `db:"parent_uuid"`
}

type LinkLayerDeviceRoute struct {
	DeviceUuid      string `db:"device_uuid"`
	DestinationCidr string `db:"destination_cidr"`
	GatewayIp       string `db:"gateway_ip"`
	Metric          int64  `db:"metric"`
}

type LinkLayerDeviceType struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type Machine struct {
	Uuid                    string     `db:"uuid"`
	Name                    string     `db:"name"`
	NetNodeUuid             string     `db:"net_node_uuid"`
	LifeId                  int64      `db:"life_id"`
	Nonce                   *string    `db:"nonce"`
	PasswordHashAlgorithmId *string    `db:"password_hash_algorithm_id"`
	PasswordHash            *string    `db:"password_hash"`
	ForceDestroyed          *bool      `db:"force_destroyed"`
	AgentStartedAt          *time.Time `db:"agent_started_at"`
	Hostname                *string    `db:"hostname"`
	KeepInstance            *bool      `db:"keep_instance"`
}

type MachineAgentPresence struct {
	MachineUuid string     `db:"machine_uuid"`
	LastSeen    *time.Time `db:"last_seen"`
}

type MachineAgentVersion struct {
	MachineUuid    string `db:"machine_uuid"`
	Version        string `db:"version"`
	ArchitectureId int64  `db:"architecture_id"`
}

type MachineCloudInstance struct {
	MachineUuid          string  `db:"machine_uuid"`
	LifeId               int64   `db:"life_id"`
	InstanceId           *string `db:"instance_id"`
	DisplayName          *string `db:"display_name"`
	Arch                 *string `db:"arch"`
	AvailabilityZoneUuid *string `db:"availability_zone_uuid"`
	CpuCores             *int64  `db:"cpu_cores"`
	CpuPower             *int64  `db:"cpu_power"`
	Mem                  *int64  `db:"mem"`
	RootDisk             *int64  `db:"root_disk"`
	RootDiskSource       *string `db:"root_disk_source"`
	VirtType             *string `db:"virt_type"`
}

type MachineCloudInstanceStatus struct {
	MachineUuid string     `db:"machine_uuid"`
	StatusId    int64      `db:"status_id"`
	Message     *string    `db:"message"`
	Data        *string    `db:"data"`
	UpdatedAt   *time.Time `db:"updated_at"`
}

type MachineCloudInstanceStatusValue struct {
	Id     *int64 `db:"id"`
	Status string `db:"status"`
}

type MachineConstraint struct {
	MachineUuid    string `db:"machine_uuid"`
	ConstraintUuid string `db:"constraint_uuid"`
}

type MachineContainerType struct {
	MachineUuid     string `db:"machine_uuid"`
	ContainerTypeId int64  `db:"container_type_id"`
}

type MachineFilesystem struct {
	MachineUuid    string `db:"machine_uuid"`
	FilesystemUuid string `db:"filesystem_uuid"`
}

type MachineLxdProfile struct {
	MachineUuid string `db:"machine_uuid"`
	Name        string `db:"name"`
	ArrayIndex  int64  `db:"array_index"`
}

type MachineManual struct {
	MachineUuid string `db:"machine_uuid"`
}

type MachineParent struct {
	MachineUuid string `db:"machine_uuid"`
	ParentUuid  string `db:"parent_uuid"`
}

type MachinePlacement struct {
	MachineUuid string `db:"machine_uuid"`
	ScopeId     int64  `db:"scope_id"`
	Directive   string `db:"directive"`
}

type MachinePlacementScope struct {
	Id    *int64 `db:"id"`
	Value string `db:"value"`
}

type MachinePlatform struct {
	MachineUuid    string  `db:"machine_uuid"`
	OsId           string  `db:"os_id"`
	Channel        *string `db:"channel"`
	ArchitectureId int64   `db:"architecture_id"`
}

type MachineRequiresReboot struct {
	MachineUuid string    `db:"machine_uuid"`
	CreatedAt   time.Time `db:"created_at"`
}

type MachineSshHostKey struct {
	Uuid        string `db:"uuid"`
	MachineUuid string `db:"machine_uuid"`
	SshKey      string `db:"ssh_key"`
}

type MachineStatus struct {
	MachineUuid string     `db:"machine_uuid"`
	StatusId    int64      `db:"status_id"`
	Message     *string    `db:"message"`
	Data        *string    `db:"data"`
	UpdatedAt   *time.Time `db:"updated_at"`
}

type MachineStatusValue struct {
	Id     *int64 `db:"id"`
	Status string `db:"status"`
}

type MachineVolume struct {
	MachineUuid string `db:"machine_uuid"`
	VolumeUuid  string `db:"volume_uuid"`
}

type Model struct {
	Uuid              string  `db:"uuid"`
	ControllerUuid    string  `db:"controller_uuid"`
	Name              string  `db:"name"`
	Qualifier         string  `db:"qualifier"`
	Type              string  `db:"type"`
	Cloud             string  `db:"cloud"`
	CloudType         string  `db:"cloud_type"`
	CloudRegion       *string `db:"cloud_region"`
	CredentialOwner   *string `db:"credential_owner"`
	CredentialName    *string `db:"credential_name"`
	IsControllerModel *bool   `db:"is_controller_model"`
}

type ModelAgent struct {
	ModelUuid               string  `db:"model_uuid"`
	PasswordHashAlgorithmId *int64  `db:"password_hash_algorithm_id"`
	PasswordHash            *string `db:"password_hash"`
}

type ModelConfig struct {
	Key   string `db:"key"`
	Value string `db:"value"`
}

type ModelConstraint struct {
	ModelUuid      string `db:"model_uuid"`
	ConstraintUuid string `db:"constraint_uuid"`
}

type ModelLife struct {
	ModelUuid string `db:"model_uuid"`
	LifeId    string `db:"life_id"`
}

type ModelMigrating struct {
	Uuid      string `db:"uuid"`
	ModelUuid string `db:"model_uuid"`
}

type ModelStoragePool struct {
	StorageKindId   int64  `db:"storage_kind_id"`
	StoragePoolUuid string `db:"storage_pool_uuid"`
}

type NetNode struct {
	Uuid string `db:"uuid"`
}

type NetNodeFqdnAddress struct {
	NetNodeUuid string `db:"net_node_uuid"`
	AddressUuid string `db:"address_uuid"`
}

type NetNodeHostnameAddress struct {
	NetNodeUuid string `db:"net_node_uuid"`
	AddressUuid string `db:"address_uuid"`
}

type NetworkAddressScope struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type ObjectStoreMetadata struct {
	Uuid   string `db:"uuid"`
	Sha256 string `db:"sha_256"`
	Sha384 string `db:"sha_384"`
	Size   int64  `db:"size"`
}

type ObjectStoreMetadataPath struct {
	Path         string `db:"path"`
	MetadataUuid string `db:"metadata_uuid"`
}

type Offer struct {
	Uuid string `db:"uuid"`
	Name string `db:"name"`
}

type OfferConnection struct {
	Uuid               string `db:"uuid"`
	OfferUuid          string `db:"offer_uuid"`
	RemoteRelationUuid string `db:"remote_relation_uuid"`
	Username           string `db:"username"`
}

type OfferEndpoint struct {
	OfferUuid    string `db:"offer_uuid"`
	EndpointUuid string `db:"endpoint_uuid"`
}

type Operation struct {
	Uuid           string     `db:"uuid"`
	OperationId    string     `db:"operation_id"`
	Summary        *string    `db:"summary"`
	EnqueuedAt     time.Time  `db:"enqueued_at"`
	StartedAt      *time.Time `db:"started_at"`
	CompletedAt    *time.Time `db:"completed_at"`
	Parallel       *bool      `db:"parallel"`
	ExecutionGroup *string    `db:"execution_group"`
}

type OperationAction struct {
	OperationUuid  string `db:"operation_uuid"`
	CharmUuid      string `db:"charm_uuid"`
	CharmActionKey string `db:"charm_action_key"`
}

type OperationMachineTask struct {
	TaskUuid    string `db:"task_uuid"`
	MachineUuid string `db:"machine_uuid"`
}

type OperationParameter struct {
	OperationUuid string `db:"operation_uuid"`
	Key           string `db:"key"`
	Value         string `db:"value"`
}

type OperationTask struct {
	Uuid          string     `db:"uuid"`
	OperationUuid string     `db:"operation_uuid"`
	TaskId        string     `db:"task_id"`
	EnqueuedAt    time.Time  `db:"enqueued_at"`
	StartedAt     *time.Time `db:"started_at"`
	CompletedAt   *time.Time `db:"completed_at"`
}

type OperationTaskLog struct {
	TaskUuid  string    `db:"task_uuid"`
	Content   string    `db:"content"`
	CreatedAt time.Time `db:"created_at"`
}

type OperationTaskOutput struct {
	TaskUuid  string `db:"task_uuid"`
	StorePath string `db:"store_path"`
}

type OperationTaskStatus struct {
	TaskUuid  string     `db:"task_uuid"`
	StatusId  int64      `db:"status_id"`
	Message   *string    `db:"message"`
	UpdatedAt *time.Time `db:"updated_at"`
}

type OperationTaskStatusValue struct {
	Id     *int64 `db:"id"`
	Status string `db:"status"`
}

type OperationUnitTask struct {
	TaskUuid string `db:"task_uuid"`
	UnitUuid string `db:"unit_uuid"`
}

type OperatorStatus struct {
	ApplicationUuid string     `db:"application_uuid"`
	StatusId        int64      `db:"status_id"`
	Message         *string    `db:"message"`
	Data            *string    `db:"data"`
	UpdatedAt       *time.Time `db:"updated_at"`
}

type Os struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type PasswordHashAlgorithm struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type PendingApplicationResource struct {
	ResourceUuid    string `db:"resource_uuid"`
	ApplicationName string `db:"application_name"`
}

type PortRange struct {
	Uuid         string  `db:"uuid"`
	ProtocolId   int64   `db:"protocol_id"`
	FromPort     *int64  `db:"from_port"`
	ToPort       *int64  `db:"to_port"`
	RelationUuid *string `db:"relation_uuid"`
	UnitUuid     string  `db:"unit_uuid"`
}

type Protocol struct {
	Id       *int64 `db:"id"`
	Protocol string `db:"protocol"`
}

type ProviderIpAddress struct {
	ProviderId  string `db:"provider_id"`
	AddressUuid string `db:"address_uuid"`
}

type ProviderLinkLayerDevice struct {
	ProviderId string `db:"provider_id"`
	DeviceUuid string `db:"device_uuid"`
}

type ProviderNetwork struct {
	Uuid              string `db:"uuid"`
	ProviderNetworkId string `db:"provider_network_id"`
}

type ProviderNetworkSubnet struct {
	SubnetUuid          string `db:"subnet_uuid"`
	ProviderNetworkUuid string `db:"provider_network_uuid"`
}

type ProviderSpace struct {
	ProviderId string `db:"provider_id"`
	SpaceUuid  string `db:"space_uuid"`
}

type ProviderSubnet struct {
	ProviderId string `db:"provider_id"`
	SubnetUuid string `db:"subnet_uuid"`
}

type Relation struct {
	Uuid            string  `db:"uuid"`
	LifeId          int64   `db:"life_id"`
	RelationId      int64   `db:"relation_id"`
	Suspended       *bool   `db:"suspended"`
	SuspendedReason *string `db:"suspended_reason"`
	ScopeId         int64   `db:"scope_id"`
}

type RelationApplicationSetting struct {
	RelationEndpointUuid string  `db:"relation_endpoint_uuid"`
	Key                  string  `db:"key"`
	Value                *string `db:"value"`
}

type RelationApplicationSettingsHash struct {
	RelationEndpointUuid string `db:"relation_endpoint_uuid"`
	Sha256               string `db:"sha256"`
}

type RelationEndpoint struct {
	Uuid         string `db:"uuid"`
	RelationUuid string `db:"relation_uuid"`
	EndpointUuid string `db:"endpoint_uuid"`
}

type RelationNetworkEgress struct {
	RelationUuid string `db:"relation_uuid"`
	Cidr         string `db:"cidr"`
}

type RelationNetworkIngress struct {
	RelationUuid string `db:"relation_uuid"`
	Cidr         string `db:"cidr"`
}

type RelationStatus struct {
	RelationUuid         string     `db:"relation_uuid"`
	RelationStatusTypeId string     `db:"relation_status_type_id"`
	Message              *string    `db:"message"`
	UpdatedAt            *time.Time `db:"updated_at"`
}

type RelationStatusType struct {
	Id   string `db:"id"`
	Name string `db:"name"`
}

type RelationUnit struct {
	Uuid                 string `db:"uuid"`
	RelationEndpointUuid string `db:"relation_endpoint_uuid"`
	UnitUuid             string `db:"unit_uuid"`
}

type RelationUnitSetting struct {
	RelationUnitUuid string  `db:"relation_unit_uuid"`
	Key              string  `db:"key"`
	Value            *string `db:"value"`
}

type RelationUnitSettingArchive struct {
	RelationUuid string  `db:"relation_uuid"`
	UnitName     string  `db:"unit_name"`
	Key          string  `db:"key"`
	Value        *string `db:"value"`
}

type RelationUnitSettingsHash struct {
	RelationUnitUuid string `db:"relation_unit_uuid"`
	Sha256           string `db:"sha256"`
}

type Removal struct {
	Uuid          string    `db:"uuid"`
	RemovalTypeId int64     `db:"removal_type_id"`
	EntityUuid    string    `db:"entity_uuid"`
	Force         int64     `db:"force"`
	ScheduledFor  time.Time `db:"scheduled_for"`
	Arg           *string   `db:"arg"`
}

type RemovalType struct {
	Id   int64  `db:"id"`
	Name string `db:"name"`
}

type ResolveMode struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type Resource struct {
	Uuid              string     `db:"uuid"`
	CharmUuid         string     `db:"charm_uuid"`
	CharmResourceName string     `db:"charm_resource_name"`
	Revision          *int64     `db:"revision"`
	OriginTypeId      int64      `db:"origin_type_id"`
	StateId           int64      `db:"state_id"`
	CreatedAt         time.Time  `db:"created_at"`
	LastPolled        *time.Time `db:"last_polled"`
}

type ResourceContainerImageMetadataStore struct {
	StorageKey   string  `db:"storage_key"`
	RegistryPath string  `db:"registry_path"`
	Username     *string `db:"username"`
	Password     *string `db:"password"`
}

type ResourceFileStore struct {
	ResourceUuid string  `db:"resource_uuid"`
	StoreUuid    string  `db:"store_uuid"`
	Size         *int64  `db:"size"`
	Sha384       *string `db:"sha384"`
}

type ResourceImageStore struct {
	ResourceUuid    string  `db:"resource_uuid"`
	StoreStorageKey string  `db:"store_storage_key"`
	Size            *int64  `db:"size"`
	Sha384          *string `db:"sha384"`
}

type ResourceOriginType struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type ResourceRetrievedBy struct {
	ResourceUuid      string `db:"resource_uuid"`
	RetrievedByTypeId int64  `db:"retrieved_by_type_id"`
	Name              string `db:"name"`
}

type ResourceRetrievedByType struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type ResourceState struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type Schema struct {
	Id        int64     `db:"id"`
	Version   int64     `db:"version"`
	Hash      string    `db:"hash"`
	UpdatedAt time.Time `db:"updated_at"`
}

type Secret struct {
	Id string `db:"id"`
}

type SecretApplicationOwner struct {
	SecretId        string  `db:"secret_id"`
	ApplicationUuid string  `db:"application_uuid"`
	Label           *string `db:"label"`
}

type SecretContent struct {
	RevisionUuid string `db:"revision_uuid"`
	Name         string `db:"name"`
	Content      string `db:"content"`
}

type SecretDeletedValueRef struct {
	RevisionUuid string `db:"revision_uuid"`
	BackendUuid  string `db:"backend_uuid"`
	RevisionId   string `db:"revision_id"`
}

type SecretGrantScopeType struct {
	Id   *int64  `db:"id"`
	Type *string `db:"type"`
}

type SecretGrantSubjectType struct {
	Id   *int64  `db:"id"`
	Type *string `db:"type"`
}

type SecretMetadata struct {
	SecretId               string    `db:"secret_id"`
	Version                int64     `db:"version"`
	Description            *string   `db:"description"`
	RotatePolicyId         int64     `db:"rotate_policy_id"`
	AutoPrune              bool      `db:"auto_prune"`
	LatestRevisionChecksum *string   `db:"latest_revision_checksum"`
	CreateTime             time.Time `db:"create_time"`
	UpdateTime             time.Time `db:"update_time"`
}

type SecretModelOwner struct {
	SecretId string  `db:"secret_id"`
	Label    *string `db:"label"`
}

type SecretPermission struct {
	SecretId      string `db:"secret_id"`
	RoleId        int64  `db:"role_id"`
	SubjectUuid   string `db:"subject_uuid"`
	SubjectTypeId int64  `db:"subject_type_id"`
	ScopeUuid     string `db:"scope_uuid"`
	ScopeTypeId   string `db:"scope_type_id"`
}

type SecretReference struct {
	SecretId             string `db:"secret_id"`
	LatestRevision       int64  `db:"latest_revision"`
	OwnerApplicationUuid string `db:"owner_application_uuid"`
}

type SecretRemoteUnitConsumer struct {
	SecretId        string `db:"secret_id"`
	UnitName        string `db:"unit_name"`
	CurrentRevision int64  `db:"current_revision"`
}

type SecretRevision struct {
	Uuid       string    `db:"uuid"`
	SecretId   string    `db:"secret_id"`
	Revision   int64     `db:"revision"`
	CreateTime time.Time `db:"create_time"`
}

type SecretRevisionExpire struct {
	RevisionUuid string    `db:"revision_uuid"`
	ExpireTime   time.Time `db:"expire_time"`
}

type SecretRevisionObsolete struct {
	RevisionUuid  string `db:"revision_uuid"`
	Obsolete      bool   `db:"obsolete"`
	PendingDelete bool   `db:"pending_delete"`
}

type SecretRole struct {
	Id   *int64  `db:"id"`
	Role *string `db:"role"`
}

type SecretRotatePolicy struct {
	Id     *int64 `db:"id"`
	Policy string `db:"policy"`
}

type SecretRotation struct {
	SecretId         string    `db:"secret_id"`
	NextRotationTime time.Time `db:"next_rotation_time"`
}

type SecretUnitConsumer struct {
	SecretId        string  `db:"secret_id"`
	SourceModelUuid string  `db:"source_model_uuid"`
	UnitUuid        string  `db:"unit_uuid"`
	Label           *string `db:"label"`
	CurrentRevision int64   `db:"current_revision"`
}

type SecretUnitOwner struct {
	SecretId string  `db:"secret_id"`
	UnitUuid string  `db:"unit_uuid"`
	Label    *string `db:"label"`
}

type SecretValueRef struct {
	RevisionUuid string `db:"revision_uuid"`
	BackendUuid  string `db:"backend_uuid"`
	RevisionId   string `db:"revision_id"`
}

type Sequence struct {
	Namespace string `db:"namespace"`
	Value     int64  `db:"value"`
}

type Space struct {
	Uuid string `db:"uuid"`
	Name string `db:"name"`
}

type StorageAttachment struct {
	Uuid                string `db:"uuid"`
	StorageInstanceUuid string `db:"storage_instance_uuid"`
	UnitUuid            string `db:"unit_uuid"`
	LifeId              int64  `db:"life_id"`
}

type StorageFilesystem struct {
	Uuid                string  `db:"uuid"`
	FilesystemId        string  `db:"filesystem_id"`
	LifeId              int64   `db:"life_id"`
	ProvisionScopeId    int64   `db:"provision_scope_id"`
	ProviderId          *string `db:"provider_id"`
	SizeMib             *int64  `db:"size_mib"`
	ObliterateOnCleanup *bool   `db:"obliterate_on_cleanup"`
}

type StorageFilesystemAttachment struct {
	Uuid                  string  `db:"uuid"`
	StorageFilesystemUuid string  `db:"storage_filesystem_uuid"`
	NetNodeUuid           string  `db:"net_node_uuid"`
	ProvisionScopeId      int64   `db:"provision_scope_id"`
	ProviderId            *string `db:"provider_id"`
	LifeId                int64   `db:"life_id"`
	MountPoint            *string `db:"mount_point"`
	ReadOnly              *bool   `db:"read_only"`
}

type StorageFilesystemStatus struct {
	FilesystemUuid string     `db:"filesystem_uuid"`
	StatusId       int64      `db:"status_id"`
	Message        *string    `db:"message"`
	UpdatedAt      *time.Time `db:"updated_at"`
}

type StorageFilesystemStatusValue struct {
	Id     *int64 `db:"id"`
	Status string `db:"status"`
}

type StorageInstance struct {
	Uuid             string  `db:"uuid"`
	CharmName        *string `db:"charm_name"`
	StorageName      string  `db:"storage_name"`
	StorageKindId    int64   `db:"storage_kind_id"`
	StorageId        string  `db:"storage_id"`
	LifeId           int64   `db:"life_id"`
	StoragePoolUuid  string  `db:"storage_pool_uuid"`
	RequestedSizeMib int64   `db:"requested_size_mib"`
}

type StorageInstanceFilesystem struct {
	StorageInstanceUuid   string `db:"storage_instance_uuid"`
	StorageFilesystemUuid string `db:"storage_filesystem_uuid"`
}

type StorageInstanceVolume struct {
	StorageInstanceUuid string `db:"storage_instance_uuid"`
	StorageVolumeUuid   string `db:"storage_volume_uuid"`
}

type StorageKind struct {
	Id   *int64 `db:"id"`
	Kind string `db:"kind"`
}

type StoragePool struct {
	Uuid     string `db:"uuid"`
	Name     string `db:"name"`
	Type     string `db:"type"`
	OriginId int64  `db:"origin_id"`
}

type StoragePoolAttribute struct {
	StoragePoolUuid string `db:"storage_pool_uuid"`
	Key             string `db:"key"`
	Value           string `db:"value"`
}

type StoragePoolOrigin struct {
	Id     int64  `db:"id"`
	Origin string `db:"origin"`
}

type StorageProvisionScope struct {
	Id    *int64 `db:"id"`
	Scope string `db:"scope"`
}

type StorageUnitOwner struct {
	StorageInstanceUuid string `db:"storage_instance_uuid"`
	UnitUuid            string `db:"unit_uuid"`
}

type StorageVolume struct {
	Uuid                string  `db:"uuid"`
	VolumeId            string  `db:"volume_id"`
	LifeId              int64   `db:"life_id"`
	ProvisionScopeId    int64   `db:"provision_scope_id"`
	ProviderId          *string `db:"provider_id"`
	SizeMib             *int64  `db:"size_mib"`
	HardwareId          *string `db:"hardware_id"`
	Wwn                 *string `db:"wwn"`
	Persistent          *bool   `db:"persistent"`
	ObliterateOnCleanup *bool   `db:"obliterate_on_cleanup"`
}

type StorageVolumeAttachment struct {
	Uuid              string  `db:"uuid"`
	StorageVolumeUuid string  `db:"storage_volume_uuid"`
	NetNodeUuid       string  `db:"net_node_uuid"`
	LifeId            int64   `db:"life_id"`
	ProvisionScopeId  int64   `db:"provision_scope_id"`
	ProviderId        *string `db:"provider_id"`
	BlockDeviceUuid   *string `db:"block_device_uuid"`
	ReadOnly          *bool   `db:"read_only"`
}

type StorageVolumeAttachmentPlan struct {
	Uuid              string `db:"uuid"`
	StorageVolumeUuid string `db:"storage_volume_uuid"`
	NetNodeUuid       string `db:"net_node_uuid"`
	LifeId            int64  `db:"life_id"`
	ProvisionScopeId  int64  `db:"provision_scope_id"`
	DeviceTypeId      *int64 `db:"device_type_id"`
}

type StorageVolumeAttachmentPlanAttr struct {
	AttachmentPlanUuid string `db:"attachment_plan_uuid"`
	Key                string `db:"key"`
	Value              string `db:"value"`
}

type StorageVolumeDeviceType struct {
	Id          *int64  `db:"id"`
	Name        string  `db:"name"`
	Description *string `db:"description"`
}

type StorageVolumeStatus struct {
	VolumeUuid string     `db:"volume_uuid"`
	StatusId   int64      `db:"status_id"`
	Message    *string    `db:"message"`
	UpdatedAt  *time.Time `db:"updated_at"`
}

type StorageVolumeStatusValue struct {
	Id     *int64 `db:"id"`
	Status string `db:"status"`
}

type Subnet struct {
	Uuid      string  `db:"uuid"`
	Cidr      string  `db:"cidr"`
	VlanTag   *int64  `db:"vlan_tag"`
	SpaceUuid *string `db:"space_uuid"`
}

type Unit struct {
	Uuid                    string  `db:"uuid"`
	Name                    string  `db:"name"`
	LifeId                  int64   `db:"life_id"`
	ApplicationUuid         string  `db:"application_uuid"`
	NetNodeUuid             string  `db:"net_node_uuid"`
	CharmUuid               string  `db:"charm_uuid"`
	PasswordHashAlgorithmId *string `db:"password_hash_algorithm_id"`
	PasswordHash            *string `db:"password_hash"`
}

type UnitAgentPresence struct {
	UnitUuid string     `db:"unit_uuid"`
	LastSeen *time.Time `db:"last_seen"`
}

type UnitAgentStatus struct {
	UnitUuid  string     `db:"unit_uuid"`
	StatusId  int64      `db:"status_id"`
	Message   *string    `db:"message"`
	Data      *string    `db:"data"`
	UpdatedAt *time.Time `db:"updated_at"`
}

type UnitAgentStatusValue struct {
	Id     *int64 `db:"id"`
	Status string `db:"status"`
}

type UnitAgentVersion struct {
	UnitUuid       string `db:"unit_uuid"`
	Version        string `db:"version"`
	ArchitectureId int64  `db:"architecture_id"`
}

type UnitPrincipal struct {
	UnitUuid      string `db:"unit_uuid"`
	PrincipalUuid string `db:"principal_uuid"`
}

type UnitResolved struct {
	UnitUuid string `db:"unit_uuid"`
	ModeId   int64  `db:"mode_id"`
}

type UnitResource struct {
	ResourceUuid string    `db:"resource_uuid"`
	UnitUuid     string    `db:"unit_uuid"`
	AddedAt      time.Time `db:"added_at"`
}

type UnitState struct {
	UnitUuid     string  `db:"unit_uuid"`
	UniterState  *string `db:"uniter_state"`
	StorageState *string `db:"storage_state"`
	SecretState  *string `db:"secret_state"`
}

type UnitStateCharm struct {
	UnitUuid string `db:"unit_uuid"`
	Key      string `db:"key"`
	Value    string `db:"value"`
}

type UnitStateRelation struct {
	UnitUuid string `db:"unit_uuid"`
	Key      string `db:"key"`
	Value    string `db:"value"`
}

type UnitStorageDirective struct {
	UnitUuid        string `db:"unit_uuid"`
	CharmUuid       string `db:"charm_uuid"`
	StorageName     string `db:"storage_name"`
	StoragePoolUuid string `db:"storage_pool_uuid"`
	SizeMib         int64  `db:"size_mib"`
	Count           int64  `db:"count"`
}

type UnitWorkloadStatus struct {
	UnitUuid  string     `db:"unit_uuid"`
	StatusId  int64      `db:"status_id"`
	Message   *string    `db:"message"`
	Data      *string    `db:"data"`
	UpdatedAt *time.Time `db:"updated_at"`
}

type UnitWorkloadVersion struct {
	UnitUuid string `db:"unit_uuid"`
	Version  string `db:"version"`
}

type VirtualPortType struct {
	Id   *int64 `db:"id"`
	Name string `db:"name"`
}

type WorkloadStatusValue struct {
	Id     *int64 `db:"id"`
	Status string `db:"status"`
}

// ModelExport aggregates all exported model row types.
type ModelExport struct {
	AgentBinaryStore                         []AgentBinaryStore
	AgentStream                              []AgentStream
	AgentVersion                             []AgentVersion
	AnnotationApplication                    []AnnotationApplication
	AnnotationCharm                          []AnnotationCharm
	AnnotationMachine                        []AnnotationMachine
	AnnotationModel                          []AnnotationModel
	AnnotationStorageFilesystem              []AnnotationStorageFilesystem
	AnnotationStorageInstance                []AnnotationStorageInstance
	AnnotationStorageVolume                  []AnnotationStorageVolume
	AnnotationUnit                           []AnnotationUnit
	Application                              []Application
	ApplicationAgent                         []ApplicationAgent
	ApplicationChannel                       []ApplicationChannel
	ApplicationConfig                        []ApplicationConfig
	ApplicationConfigHash                    []ApplicationConfigHash
	ApplicationConstraint                    []ApplicationConstraint
	ApplicationController                    []ApplicationController
	ApplicationEndpoint                      []ApplicationEndpoint
	ApplicationExposedEndpointCidr           []ApplicationExposedEndpointCidr
	ApplicationExposedEndpointSpace          []ApplicationExposedEndpointSpace
	ApplicationExtraEndpoint                 []ApplicationExtraEndpoint
	ApplicationPlatform                      []ApplicationPlatform
	ApplicationRemoteConsumer                []ApplicationRemoteConsumer
	ApplicationRemoteOfferer                 []ApplicationRemoteOfferer
	ApplicationRemoteOffererRelationMacaroon []ApplicationRemoteOffererRelationMacaroon
	ApplicationRemoteOffererStatus           []ApplicationRemoteOffererStatus
	ApplicationResource                      []ApplicationResource
	ApplicationScale                         []ApplicationScale
	ApplicationSetting                       []ApplicationSetting
	ApplicationStatus                        []ApplicationStatus
	ApplicationStorageDirective              []ApplicationStorageDirective
	ApplicationWorkloadVersion               []ApplicationWorkloadVersion
	Architecture                             []Architecture
	AvailabilityZone                         []AvailabilityZone
	AvailabilityZoneSubnet                   []AvailabilityZoneSubnet
	BlockCommand                             []BlockCommand
	BlockCommandType                         []BlockCommandType
	BlockDevice                              []BlockDevice
	BlockDeviceLinkDevice                    []BlockDeviceLinkDevice
	ChangeLog                                []ChangeLog
	ChangeLogEditType                        []ChangeLogEditType
	ChangeLogNamespace                       []ChangeLogNamespace
	ChangeLogWitness                         []ChangeLogWitness
	Charm                                    []Charm
	CharmAction                              []CharmAction
	CharmCategory                            []CharmCategory
	CharmConfig                              []CharmConfig
	CharmConfigType                          []CharmConfigType
	CharmContainer                           []CharmContainer
	CharmContainerMount                      []CharmContainerMount
	CharmDevice                              []CharmDevice
	CharmDownloadInfo                        []CharmDownloadInfo
	CharmExtraBinding                        []CharmExtraBinding
	CharmHash                                []CharmHash
	CharmManifestBase                        []CharmManifestBase
	CharmMetadata                            []CharmMetadata
	CharmProvenance                          []CharmProvenance
	CharmRelation                            []CharmRelation
	CharmRelationRole                        []CharmRelationRole
	CharmRelationScope                       []CharmRelationScope
	CharmResource                            []CharmResource
	CharmResourceKind                        []CharmResourceKind
	CharmRunAsKind                           []CharmRunAsKind
	CharmSource                              []CharmSource
	CharmStorage                             []CharmStorage
	CharmStorageKind                         []CharmStorageKind
	CharmStorageProperty                     []CharmStorageProperty
	CharmTag                                 []CharmTag
	CharmTerm                                []CharmTerm
	Constraint                               []Constraint
	ConstraintSpace                          []ConstraintSpace
	ConstraintTag                            []ConstraintTag
	ConstraintZone                           []ConstraintZone
	ContainerType                            []ContainerType
	DeviceConstraint                         []DeviceConstraint
	DeviceConstraintAttribute                []DeviceConstraintAttribute
	FqdnAddress                              []FqdnAddress
	HashKind                                 []HashKind
	HostnameAddress                          []HostnameAddress
	InstanceTag                              []InstanceTag
	IpAddress                                []IpAddress
	IpAddressConfigType                      []IpAddressConfigType
	IpAddressOrigin                          []IpAddressOrigin
	IpAddressScope                           []IpAddressScope
	IpAddressType                            []IpAddressType
	K8sPod                                   []K8sPod
	K8sPodPort                               []K8sPodPort
	K8sPodStatus                             []K8sPodStatus
	K8sPodStatusValue                        []K8sPodStatusValue
	K8sService                               []K8sService
	Life                                     []Life
	LinkLayerDevice                          []LinkLayerDevice
	LinkLayerDeviceDnsAddress                []LinkLayerDeviceDnsAddress
	LinkLayerDeviceDnsDomain                 []LinkLayerDeviceDnsDomain
	LinkLayerDeviceParent                    []LinkLayerDeviceParent
	LinkLayerDeviceRoute                     []LinkLayerDeviceRoute
	LinkLayerDeviceType                      []LinkLayerDeviceType
	Machine                                  []Machine
	MachineAgentPresence                     []MachineAgentPresence
	MachineAgentVersion                      []MachineAgentVersion
	MachineCloudInstance                     []MachineCloudInstance
	MachineCloudInstanceStatus               []MachineCloudInstanceStatus
	MachineCloudInstanceStatusValue          []MachineCloudInstanceStatusValue
	MachineConstraint                        []MachineConstraint
	MachineContainerType                     []MachineContainerType
	MachineFilesystem                        []MachineFilesystem
	MachineLxdProfile                        []MachineLxdProfile
	MachineManual                            []MachineManual
	MachineParent                            []MachineParent
	MachinePlacement                         []MachinePlacement
	MachinePlacementScope                    []MachinePlacementScope
	MachinePlatform                          []MachinePlatform
	MachineRequiresReboot                    []MachineRequiresReboot
	MachineSshHostKey                        []MachineSshHostKey
	MachineStatus                            []MachineStatus
	MachineStatusValue                       []MachineStatusValue
	MachineVolume                            []MachineVolume
	Model                                    []Model
	ModelAgent                               []ModelAgent
	ModelConfig                              []ModelConfig
	ModelConstraint                          []ModelConstraint
	ModelLife                                []ModelLife
	ModelMigrating                           []ModelMigrating
	ModelStoragePool                         []ModelStoragePool
	NetNode                                  []NetNode
	NetNodeFqdnAddress                       []NetNodeFqdnAddress
	NetNodeHostnameAddress                   []NetNodeHostnameAddress
	NetworkAddressScope                      []NetworkAddressScope
	ObjectStoreMetadata                      []ObjectStoreMetadata
	ObjectStoreMetadataPath                  []ObjectStoreMetadataPath
	Offer                                    []Offer
	OfferConnection                          []OfferConnection
	OfferEndpoint                            []OfferEndpoint
	Operation                                []Operation
	OperationAction                          []OperationAction
	OperationMachineTask                     []OperationMachineTask
	OperationParameter                       []OperationParameter
	OperationTask                            []OperationTask
	OperationTaskLog                         []OperationTaskLog
	OperationTaskOutput                      []OperationTaskOutput
	OperationTaskStatus                      []OperationTaskStatus
	OperationTaskStatusValue                 []OperationTaskStatusValue
	OperationUnitTask                        []OperationUnitTask
	OperatorStatus                           []OperatorStatus
	Os                                       []Os
	PasswordHashAlgorithm                    []PasswordHashAlgorithm
	PendingApplicationResource               []PendingApplicationResource
	PortRange                                []PortRange
	Protocol                                 []Protocol
	ProviderIpAddress                        []ProviderIpAddress
	ProviderLinkLayerDevice                  []ProviderLinkLayerDevice
	ProviderNetwork                          []ProviderNetwork
	ProviderNetworkSubnet                    []ProviderNetworkSubnet
	ProviderSpace                            []ProviderSpace
	ProviderSubnet                           []ProviderSubnet
	Relation                                 []Relation
	RelationApplicationSetting               []RelationApplicationSetting
	RelationApplicationSettingsHash          []RelationApplicationSettingsHash
	RelationEndpoint                         []RelationEndpoint
	RelationNetworkEgress                    []RelationNetworkEgress
	RelationNetworkIngress                   []RelationNetworkIngress
	RelationStatus                           []RelationStatus
	RelationStatusType                       []RelationStatusType
	RelationUnit                             []RelationUnit
	RelationUnitSetting                      []RelationUnitSetting
	RelationUnitSettingArchive               []RelationUnitSettingArchive
	RelationUnitSettingsHash                 []RelationUnitSettingsHash
	Removal                                  []Removal
	RemovalType                              []RemovalType
	ResolveMode                              []ResolveMode
	Resource                                 []Resource
	ResourceContainerImageMetadataStore      []ResourceContainerImageMetadataStore
	ResourceFileStore                        []ResourceFileStore
	ResourceImageStore                       []ResourceImageStore
	ResourceOriginType                       []ResourceOriginType
	ResourceRetrievedBy                      []ResourceRetrievedBy
	ResourceRetrievedByType                  []ResourceRetrievedByType
	ResourceState                            []ResourceState
	Schema                                   []Schema
	Secret                                   []Secret
	SecretApplicationOwner                   []SecretApplicationOwner
	SecretContent                            []SecretContent
	SecretDeletedValueRef                    []SecretDeletedValueRef
	SecretGrantScopeType                     []SecretGrantScopeType
	SecretGrantSubjectType                   []SecretGrantSubjectType
	SecretMetadata                           []SecretMetadata
	SecretModelOwner                         []SecretModelOwner
	SecretPermission                         []SecretPermission
	SecretReference                          []SecretReference
	SecretRemoteUnitConsumer                 []SecretRemoteUnitConsumer
	SecretRevision                           []SecretRevision
	SecretRevisionExpire                     []SecretRevisionExpire
	SecretRevisionObsolete                   []SecretRevisionObsolete
	SecretRole                               []SecretRole
	SecretRotatePolicy                       []SecretRotatePolicy
	SecretRotation                           []SecretRotation
	SecretUnitConsumer                       []SecretUnitConsumer
	SecretUnitOwner                          []SecretUnitOwner
	SecretValueRef                           []SecretValueRef
	Sequence                                 []Sequence
	Space                                    []Space
	StorageAttachment                        []StorageAttachment
	StorageFilesystem                        []StorageFilesystem
	StorageFilesystemAttachment              []StorageFilesystemAttachment
	StorageFilesystemStatus                  []StorageFilesystemStatus
	StorageFilesystemStatusValue             []StorageFilesystemStatusValue
	StorageInstance                          []StorageInstance
	StorageInstanceFilesystem                []StorageInstanceFilesystem
	StorageInstanceVolume                    []StorageInstanceVolume
	StorageKind                              []StorageKind
	StoragePool                              []StoragePool
	StoragePoolAttribute                     []StoragePoolAttribute
	StoragePoolOrigin                        []StoragePoolOrigin
	StorageProvisionScope                    []StorageProvisionScope
	StorageUnitOwner                         []StorageUnitOwner
	StorageVolume                            []StorageVolume
	StorageVolumeAttachment                  []StorageVolumeAttachment
	StorageVolumeAttachmentPlan              []StorageVolumeAttachmentPlan
	StorageVolumeAttachmentPlanAttr          []StorageVolumeAttachmentPlanAttr
	StorageVolumeDeviceType                  []StorageVolumeDeviceType
	StorageVolumeStatus                      []StorageVolumeStatus
	StorageVolumeStatusValue                 []StorageVolumeStatusValue
	Subnet                                   []Subnet
	Unit                                     []Unit
	UnitAgentPresence                        []UnitAgentPresence
	UnitAgentStatus                          []UnitAgentStatus
	UnitAgentStatusValue                     []UnitAgentStatusValue
	UnitAgentVersion                         []UnitAgentVersion
	UnitPrincipal                            []UnitPrincipal
	UnitResolved                             []UnitResolved
	UnitResource                             []UnitResource
	UnitState                                []UnitState
	UnitStateCharm                           []UnitStateCharm
	UnitStateRelation                        []UnitStateRelation
	UnitStorageDirective                     []UnitStorageDirective
	UnitWorkloadStatus                       []UnitWorkloadStatus
	UnitWorkloadVersion                      []UnitWorkloadVersion
	VirtualPortType                          []VirtualPortType
	WorkloadStatusValue                      []WorkloadStatusValue
}
