// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/internal/worker/apiremotecaller (interfaces: APIRemoteSubscriber)
//
// Generated by this command:
//
//	mockgen -typed -package controllerpresence -destination caller_mocks_test.go github.com/juju/juju/internal/worker/apiremotecaller APIRemoteSubscriber
//

// Package controllerpresence is a generated GoMock package.
package controllerpresence

import (
	reflect "reflect"

	apiremotecaller "github.com/juju/juju/internal/worker/apiremotecaller"
	gomock "go.uber.org/mock/gomock"
)

// MockAPIRemoteSubscriber is a mock of APIRemoteSubscriber interface.
type MockAPIRemoteSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockAPIRemoteSubscriberMockRecorder
}

// MockAPIRemoteSubscriberMockRecorder is the mock recorder for MockAPIRemoteSubscriber.
type MockAPIRemoteSubscriberMockRecorder struct {
	mock *MockAPIRemoteSubscriber
}

// NewMockAPIRemoteSubscriber creates a new mock instance.
func NewMockAPIRemoteSubscriber(ctrl *gomock.Controller) *MockAPIRemoteSubscriber {
	mock := &MockAPIRemoteSubscriber{ctrl: ctrl}
	mock.recorder = &MockAPIRemoteSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIRemoteSubscriber) EXPECT() *MockAPIRemoteSubscriberMockRecorder {
	return m.recorder
}

// GetAPIRemotes mocks base method.
func (m *MockAPIRemoteSubscriber) GetAPIRemotes() ([]apiremotecaller.RemoteConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIRemotes")
	ret0, _ := ret[0].([]apiremotecaller.RemoteConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPIRemotes indicates an expected call of GetAPIRemotes.
func (mr *MockAPIRemoteSubscriberMockRecorder) GetAPIRemotes() *MockAPIRemoteSubscriberGetAPIRemotesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIRemotes", reflect.TypeOf((*MockAPIRemoteSubscriber)(nil).GetAPIRemotes))
	return &MockAPIRemoteSubscriberGetAPIRemotesCall{Call: call}
}

// MockAPIRemoteSubscriberGetAPIRemotesCall wrap *gomock.Call
type MockAPIRemoteSubscriberGetAPIRemotesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIRemoteSubscriberGetAPIRemotesCall) Return(arg0 []apiremotecaller.RemoteConnection, arg1 error) *MockAPIRemoteSubscriberGetAPIRemotesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIRemoteSubscriberGetAPIRemotesCall) Do(f func() ([]apiremotecaller.RemoteConnection, error)) *MockAPIRemoteSubscriberGetAPIRemotesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIRemoteSubscriberGetAPIRemotesCall) DoAndReturn(f func() ([]apiremotecaller.RemoteConnection, error)) *MockAPIRemoteSubscriberGetAPIRemotesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Subscribe mocks base method.
func (m *MockAPIRemoteSubscriber) Subscribe() (apiremotecaller.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(apiremotecaller.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockAPIRemoteSubscriberMockRecorder) Subscribe() *MockAPIRemoteSubscriberSubscribeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockAPIRemoteSubscriber)(nil).Subscribe))
	return &MockAPIRemoteSubscriberSubscribeCall{Call: call}
}

// MockAPIRemoteSubscriberSubscribeCall wrap *gomock.Call
type MockAPIRemoteSubscriberSubscribeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIRemoteSubscriberSubscribeCall) Return(arg0 apiremotecaller.Subscription, arg1 error) *MockAPIRemoteSubscriberSubscribeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIRemoteSubscriberSubscribeCall) Do(f func() (apiremotecaller.Subscription, error)) *MockAPIRemoteSubscriberSubscribeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIRemoteSubscriberSubscribeCall) DoAndReturn(f func() (apiremotecaller.Subscription, error)) *MockAPIRemoteSubscriberSubscribeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
